services:
  - type: web
    name: appServicios
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn primerProducto01.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4