# Generated by Django 4.2.4 on 2023-09-27 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_admin', '0002_alter_user_models_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_models',
            name='update_at',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 20, 45, 37, 167704)),
        ),
    ]
