# Generated by Django 4.2.4 on 2023-09-26 04:25

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Img_reciclaje_app')),
                ('information', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(default=datetime.datetime(2023, 9, 25, 22, 25, 15, 974169))),
            ],
        ),
    ]
