# Generated by Django 4.2.4 on 2023-09-27 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Reciclaje_I', '0002_alter_category_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='update_at',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 20, 45, 37, 176545)),
        ),
    ]
