# Generated by Django 4.2.4 on 2023-10-04 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Reciclaje_I', '0012_alter_category_img_alter_category_update_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
