# Generated by Django 4.2.4 on 2023-10-04 03:06

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Api_Reciclaje_I', '0013_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='ImageCategory')),
                ('information', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(default=datetime.datetime(2023, 10, 3, 21, 6, 23, 68528))),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
