# Generated by Django 4.2.4 on 2023-10-04 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Reciclaje_I', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2023, 10, 3, 21, 8, 17, 283670)),
        ),
    ]
