# Generated by Django 4.2.4 on 2023-10-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log_categorias',
        ),
    ]
