# Generated by Django 4.2.4 on 2023-10-04 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_delete_log_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(blank=True, editable=False)),
                ('information', models.TextField(editable=False)),
                ('description', models.CharField(editable=False, max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(default=datetime.datetime(2023, 10, 3, 21, 18, 26, 21507), editable=False)),
                ('name', models.CharField(editable=False, max_length=50)),
                ('request_method', models.CharField(editable=False, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='access_violation',
        ),
        migrations.DeleteModel(
            name='Historial_Log_Actions',
        ),
        migrations.DeleteModel(
            name='Session_log',
        ),
    ]
