# Generated by Django 4.2.4 on 2023-10-04 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_log_categorias_delete_access_violation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_categorias',
            name='update_at',
        ),
        migrations.AddField(
            model_name='log_categorias',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2023, 10, 3, 21, 19, 34, 114806), editable=False),
        ),
    ]
