# Generated by Django 4.2.4 on 2023-10-04 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_remove_log_categorias_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_categorias',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2023, 10, 3, 21, 26, 15, 472219), editable=False),
        ),
    ]
