# Generated by Django 4.2.4 on 2023-10-04 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_log_categorias_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_categorias',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='log_categorias',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2023, 10, 3, 22, 16, 53, 783495), editable=False),
        ),
    ]
