# Generated by Django 4.2.4 on 2023-10-04 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_alter_log_categorias_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_categorias',
            name='img',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='log_categorias',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2023, 10, 3, 23, 5, 53, 292166), editable=False),
        ),
    ]
