# Generated by Django 4.2.4 on 2023-10-21 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_alter_log_categorias_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_categorias',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2023, 10, 21, 5, 55, 45, 400634), editable=False),
        ),
    ]
